serenity {
    report {
       accessibility = true
    },
    requirement {
        types = "epic, feature"
    },
    project {
        name = "automationexercise"
        outputDirectory = "target/site/serenity"
        specDirectory = "tests"
    }
}